language: node_js
sudo: false
addons:
  firefox: "41.0"
node_js:
  - "4"
  - "5"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: npm run test-ci
